POST  http://127.0.0.1:8000/api/users/ HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY4OTU4NzU1LCJqdGkiOiIwNmFhNTdlN2ZiYTA0ZmYwOWY1ZTI0NzZmNzZkYWIwNSIsInVzZXJfaWQiOjF9.1ULHjdZGU3v7xxW-TReSXdp6F8ls6SoESmchXdVcKYQ

{


} 