# Generated by Django 4.1.3 on 2022-11-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название актива')),
                ('price', models.FloatField(validators=[purchase.validators.validate_positive], verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[purchase.validators.validate_positive], verbose_name='Количество')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_owner', to='purchase.active', verbose_name='Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_active', to=settings.AUTH_USER_MODEL, verbose_name='Держатель')),
            ],
        ),
        migrations.AddField(
            model_name='active',
            name='owner',
            field=models.ManyToManyField(through='purchase.ActiveOwner', to=settings.AUTH_USER_MODEL, verbose_name='Держатель'),
        ),
    ]
